export const ADD_BOOKMARKS = "ADD_BOOKMARKS";
export const FETCH_BOOKMARKS = "FETCH_BOOKMARKS";
export const CREATE_USER = "CREATE_USER";

export const REQUESTED_BOOKMARK = "REQUEST_BOOKMARK";
export const REQUESTED_BOOKMARK_SUCCEEDED = "REQUEST_BOOKMARK_SUCCEEDED";
export const REQUESTED_BOOKMARK_FAILED = "REQUEST_BOOKMARK_FAILED";

export const REQUEST_CTEATE_USER = "REQUEST_CTEATE_USER";
export const REQUEST_CTEATE_USER_SUCCEEDED = "REQUEST_CTEATE_USER_SUCCEEDED";
export const REQUEST_CTEATE_USER_FAILED = "REQUEST_CTEATE_USER_FAILED";
